### ISSUE TITLE
Plonk: list of suggested changes

### ISSUE THREAD

**Issue by vesselinux** [clearmatics/libsnark#52]
1. Have explicit `struct` members of the `a,b,c` polynomials currently stored as a single vector `W_polys_blinded_at_secret_g1[a,b,c]` in the `plonk_proof` class. Similarly, have explicit `struct` members for the `q_L, q_R, q_O, q_M, a_C` selector polynomials currently stored as a single vector `Q_polys` in the `circuit` struct.

2. Do not store the Lagrange basis `L_basis` explicitly (e.g. as part of the `srs` class and `circuit_t` struct). Instead compute it on-the-fly as needed. For the purpose store the domain instead (obtained through `libfqfft::get_evaluation_domain<Field>()`) in the `srs` and `circuit_t` and pass this as input to functions that use the `L_basis` parameter.

3. Related to 2.:  create the `domain` once (using `libfqfft::get_evaluation_domain<Field>()`) and carry it around as necessary. See https://github.com/clearmatics/libsnark/pull/49#discussion_r917882917

4. In all header files: leave only functions that are externally visible to calling code. If a function is only used "internally" in the implementation then just leave it in the `.tcc` (and not in the `.hpp`), potentially in the `internal namespace` (to hide it from other code). See also discussion: https://github.com/clearmatics/libsnark/pull/49#discussion_r916900049

5. Move the `print_vector` function https://github.com/clearmatics/libsnark/blob/plonk/libsnark/zk_proof_systems/plonk/utils.tcc#L19-L25 to `libff/.../field_utils.hpp`.  (Nice print functions in libff clearmatics/libff#70)

6. Move the `plonk` main directory from `zk_proof_systems/` to `zk_proof_systems/ppzksnark/` since technically Plonk is a pre-processed zk-SNARK (ppzksnark).

7. Make sure that all functions do not rely on the caller for allocating the correct sizes of the return parameters. Make the latter to be allocated inside the functions that compute them. See also https://github.com/clearmatics/libsnark/pull/49#discussion_r917897577

8. When throwing an exception, it should not be up to the function that throws it to decide how it should be handled. Catch and handle must be done by the caller instead, who may wish to handle it in some way other than exiting the process, like retrying. See https://github.com/clearmatics/libsnark/pull/49#discussion_r919922215 , https://github.com/clearmatics/libsnark/pull/49#discussion_r917888375 , https://github.com/clearmatics/libsnark/pull/49#discussion_r918072765

9. Break down the long functions `plonk_prover<ppT>::round_five()` and `plonk_prover<ppT>::round_three()` into several sub-functions for the purposes of unit testing and readability (see next). See https://github.com/clearmatics/libsnark/pull/49#discussion_r919995415

10. Have a separate unit test under `tests/` to verify the value of `r_poly,` `W_zeta` and `W_zeta_omega` in `plonk_prover<ppT>::round_five()`. See https://github.com/clearmatics/libsnark/pull/49#discussion_r918118336 and https://github.com/clearmatics/libsnark/pull/49#discussion_r919995415

11. Compute the challenges `alpha, beta, gamma, zeta, nu, u` using a hash function rather than passing them as pre-computed inputs as part of the `transcript_hash_t` structure. The latter is done now for the purposes of unit testing. In the long run we might want something like a `transcript_hasher` which can accept field and group elements as they are available, and then output a digest when required. See discussion at https://github.com/clearmatics/libsnark/pull/49#discussion_r918132276 and https://github.com/clearmatics/libsnark/pull/49#discussion_r920012855

**Comment by dtebbs** [comment]
For the immediate future:
- #57 error handling (8 above)
- #56 transaction hasher (11 above)

- #58 Basic tidy up issue (1, 4, 7, 8 above)
- #55 error handling + lagrange basis: (2, 3 above)
- #59 print issue in libff (5 above)

(ignore: 9, 10 for now.)

**Comment by vesselinux** [comment]
Issue broken down into 5 new issues according to the list [above](https://github.com/clearmatics/libsnark/issues/52#issuecomment-1188785111) and closed.
