### ISSUE TITLE
Remove domain from plonk srs?

### ISSUE THREAD

**Issue by dtebbs** [clearmatics/libsnark#69]
Plonk implementation:
- [ ] check where domain is created / used
- [ ] can we create once and use in multiple places?

PRs:
- #70

**Comment by vesselinux** [comment]
Regarding the first point: the `domain` is created and used in function 

- `plonk_interpolate_polynomial_from_points` https://github.com/clearmatics/libsnark/blob/69-plonk-remove-domain-from-srs/libsnark/zk_proof_systems/plonk/utils.tcc#L47

The above is called inside the following functions:

- `plonk_compute_selector_polynomials` https://github.com/clearmatics/libsnark/blob/69-plonk-remove-domain-from-srs/libsnark/zk_proof_systems/plonk/utils.tcc#L63
- `plonk_compute_public_input_polynomial` https://github.com/clearmatics/libsnark/blob/69-plonk-remove-domain-from-srs/libsnark/zk_proof_systems/plonk/utils.tcc#L81
- `plonk_compute_permutation_polynomials` https://github.com/clearmatics/libsnark/blob/69-plonk-remove-domain-from-srs/libsnark/zk_proof_systems/plonk/utils.tcc#L186

Regarding the second point, if we want keep the `domain` in the `srs` and reuse it, then we'll need to modify the above three functions to accept the `srs` as an input parameter. I would like to discuss the efficiency gain after such a change before making it. For the moment the `domain` has been removed from the `srs` -- see PR #70.

**Comment by dtebbs** [comment]
How about creating the domain once at the start of the most "outer" function that uses it, and then passing the domain to each function that needs it?

**Comment by vesselinux** [comment]
> How about creating the domain once at the start of the most "outer" function that uses it, and then passing the domain to each function that needs it?

Hmm, interesting idea! Should be feasible. We'll post if I encounter any unforeseen complications.

**Comment by vesselinux** [comment]
Recomputation of domain parameter removed at multiple places and added as an additional input parameter to the following functions:

```
- srs<ppT> plonk_srs_derive_from_usrs
- void plonk_interpolate_polynomial_from_points(
- round_two_out_t<ppT> plonk_prover<ppT>::round_two(
- plonk_proof<ppT> plonk_prover<ppT>::compute_proof(
- round_one_out_t<ppT> plonk_prover<ppT>::round_one(
- std::vector<polynomial<FieldT>> plonk_compute_selector_polynomials(
- void plonk_compute_public_input_polynomial(
- std::vector<polynomial<FieldT>> plonk_compute_permutation_polynomials(
- step_five_out_t<ppT> plonk_verifier<ppT>::step_five(
- bool plonk_verifier<ppT>::verify_proof(
```

Re-review requested.
