### ISSUE TITLE
Plonk: helper function plonk_prepare_matrix to build gates matrix

### ISSUE THREAD

**Issue by vesselinux** [clearmatics/libsnark#89]
Implement helper function `plonk_prepare_matrix` to:

1. Prepare a gates matrix that has the top $L$ rows corresponding to $L$ Plonk public input gates (for a circuit with $L$ public inputs)

The caller will then manually:

1. Fill in the remaining rows from $L+1$ to $N$ (for a circuit with $N$ gates) of the gates matrix with the remaining Plonk gates describing the circuit (add, multiply, multiply-by-constant, dummy)

1. Generate the wire permutation (copy constraints) including the public inputs

1. Pass the constructed gates matrix, together with the wire permutation and public input indices as an input to function `plonk_srs_derive_from_usrs` (see Issue #88)

**Comment by dtebbs** [comment]
First step towards #95
